<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="BLRKEC334480D" ignored="1" name="Command line test c07e1876-4ed8-4697-aaa4-91401c896a96" tests="1" failures="1" timestamp="06 Aug 2018 12:29:29 GMT" time="201.031" errors="0">
  <testcase name="searchProduct" time="153.966" classname="app.tests.EndToEndTestCases">
    <failure type="java.lang.AssertionError" message="Sign Out is unsuccessful; expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Sign Out is unsuccessful; expected [true] but found [false]
	at app.pages.HomePage.signOut(Unknown Source)
	at app.tests.EndToEndTestCases.searchProduct(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 13 stack frames]]>
    </failure>
  </testcase> <!-- searchProduct -->
  <testcase name="checkoutProduct" time="0.0" classname="app.tests.EndToEndTestCases">
    <ignored/>
  </testcase> <!-- checkoutProduct -->
</testsuite> <!-- Command line test c07e1876-4ed8-4697-aaa4-91401c896a96 -->
